### ISSUE TITLE
Running SiamDW_D in default configuration

### ISSUE THREAD

**Issue by maxizi** [researchmm/VOT-2019-SiamDW_X#5]
Hi folks,

I want to run the SiamDW_D on the VOT2019-RGBD dataset in the standard configuration. The setup was successful, however, I still struggle to make the tracker run with the "parallel_test.py" script without making any changes. I downloaded the pretrained models. The delivered pretrained network seems to be different from the configuration in python parallel_test.py (see the screenshot and the error trace).

Can you provide either the model configuration that you have been using with the "networks/FPN/rpn_r50_fpn_2x.pth" network or the model parameters for the "../libs/FPNlib/configs/rpn_r50_fpn_1x.py" setup?

Thanks for taking care,
Max

Screenshot from "senet_far.py":
![image](https://user-images.githubusercontent.com/36971632/75176740-02cb9100-5735-11ea-9f87-a6a550fdca5d.png)

Tracker: far_fusion far_fusion 0 ,  Sequence: bicycle2_outside
longterm term tracking
Traceback (most recent call last):
  File "/home/maxi/siamdw_d/SiamDW_D/libs/mmcv/runner/checkpoint.py", line 71, in load_state_dict
    own_state[name].copy_(param)
RuntimeError: The size of tensor a (6) must match the size of tensor b (3) at non-singleton dimension 0

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/home/maxi/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "/home/maxi/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/maxi/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/home/maxi/anaconda3/envs/siamdwd/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/maxi/anaconda3/envs/siamdwd/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/maxi/anaconda3/envs/siamdwd/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maxi/siamdw_d/SiamDW_D/test/parallel_test.py", line 146, in <module>
    one_test('0', 5)
  File "/home/maxi/siamdw_d/SiamDW_D/test/parallel_test.py", line 113, in one_test
    tracked_bb, exec_times, scores, record = tracker.run(seq, rgbd_flag=args.rgbd_flag)
  File "/home/maxi/siamdw_d/SiamDW_D/libs/core/tracker_test.py", line 38, in run
    output_bb, execution_times, scores, record = tracker.track_sequence_rgbd(seq)
  File "/home/maxi/siamdw_d/SiamDW_D/libs/core/base/basetracker.py", line 118, in track_sequence_rgbd
    self.initialize_rgbd(raw_im, image, depth_im, gt_bbox, init_online=False)
  File "/home/maxi/siamdw_d/SiamDW_D/libs/core/far_fusion/far_fusion.py", line 17, in initialize_rgbd
    self.tracker_senet.initialize_rgbd(raw_im, image, depth_im, state, *args, **kwargs)
  File "/home/maxi/siamdw_d/SiamDW_D/libs/core/senet_far/senet_far.py", line 294, in initialize_rgbd
    load_checkpoint(self.fpn_model, checkpoint, map_location='cpu')
  File "/home/maxi/siamdw_d/SiamDW_D/libs/mmcv/runner/checkpoint.py", line 152, in load_checkpoint
    load_state_dict(model, state_dict, strict, logger)
  File "/home/maxi/siamdw_d/SiamDW_D/libs/mmcv/runner/checkpoint.py", line 77, in load_state_dict
    name, own_state[name].size(), param.size()))
RuntimeError: While copying the parameter named rpn_head.rpn_cls.weight, whose dimensions in the model are torch.Size([6, 256, 1, 1]) and whose dimensions in the checkpoint are torch.Size([3, 256, 1, 1]).
[1]    29230 terminated  env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1   --default --client --host 
```

**Comment by maxizi** [comment]
Other than that, providing the training code would also help, as I then could train the model myself.

Thanks for your support.
